### ISSUE TITLE
Can't start program

### ISSUE THREAD

**Issue by tgillian** [Foulest/RepairKit#8] opened 2024-06-15 18:04 UTC
**Before you submit this issue, please make sure you have done the following:**

- [x ] I am using the latest version of RepairKit
- x[ ] I am using Windows 10 or higher as my operating system
- [x ] I have searched the issue tracker for a similar issue
- [x ] I have excluded RepairKit from my antivirus software

**Describe the bug**
When I click on the program Windows asks if I want to allow this app from an unknown publisher to make changes to this computer.  I click on yes.  The screen gives the busy blue circle on screen and then it just goes away.

**Expected behavior**
I expected the program to start.

**Actual behavior**
Nothing!  It just goes away

**To Reproduce**

1. Go to c:\temp\repairkit
2. Click on RepairKit-1.0.6.exe
3. Windows asks if I want to allow program to make changes to my computer I say yes
4. Nothing

**Screenshots**
If applicable, add screenshots or animated GIFs to help explain your problem.

**Additional context**
Have a Dell G7 15 Laptop.  Running  Microsoft Windows 11 Professional Workstation (x64) Build 22635.3720

**Comment by Foulest** [comment] 2024-06-15 18:58
It's because you were running it from the `%temp%\RepairKit` directory. Fixed in the latest version @tgillian.

**Comment by tgillian** [comment] 2024-06-15 22:33
Well, I must admit I am not the most talented in the computer field.  However, a couple of comments.  First, the temp file I was using was not the system temp file (%temp%) but a folder I created on the C: drive.  Second, I downloaded the version 1.0.7.  I have tried to run it from my NAS drive, a USB drive (which is where I probably would usually run it from, and a c:\Repairkit-1.0.7 folder.  They all start to run it and then just go away.  No errors, no messages, nothing.  Guess I was not meant to use/look at your program.

Thanks for the answer though! I appreciate it.

**Comment by Foulest** [comment] 2024-06-16 01:40
I can't replicate your error when starting RepairKit from the `C:\RepairKit-1.0.7` directory or running it from a USB drive. The temp directory was a legitimate problem; it is fixed even though it wasn't the cause of your problem.

I've released a new version of RepairKit that outputs a RepairKit.log file used for debugging in the `%temp%` directory. Run it and attach it to this issue thread when you can.

**Comment by tgillian** [comment] 2024-06-16 02:21
No change attached is the log.  Hope it means something to you.  I looked at the log and nothing jumped out at me.  But, I don't know what the program does.
[RepairKit.log](https://github.com/user-attachments/files/15855953/RepairKit.log)

I'm interested in what happened.
Thanks for the help!

**Comment by Foulest** [comment] 2024-06-16 02:35
Interesting. It just.. ends before it can draw the GUI at all.

Here, run this [newly compiled version](https://www.dropbox.com/scl/fi/le7mcyq5svv0h7g7sv379/RepairKit-1.0.8.zip?rlkey=e2ppgwxg8errcjeh61d6ymfq7&st=r449n0se&dl=1) attached and post the log file. Let's see if we can get more information.

**Comment by tgillian** [comment] 2024-06-16 17:44
Well, I ran it just as you wanted.  Ran it from D:\RepairKit-1.0.8.  Ran it as Admin.
Sorry, no change.  Just terminated in the log.  Find the log attached.
[RepairKit.log](https://github.com/user-attachments/files/15859257/RepairKit.log)

**Comment by Foulest** [comment] 2024-06-16 18:25
Well... Clearly, some exceptions are being thrown but not caught. Interestingly, your log file is missing the security software section. Let's try something to guarantee that we catch whatever is happening absolutely.

Download and extract this [newly compiled zip file](https://www.dropbox.com/scl/fi/vc0dw0od707byhlajl51w/RepairKit-1.0.8-Test.zip?rlkey=moh7s4vg9k2vaicyqkggq0bns&st=sbcdn4rq&dl=1) and run the `start.bat` file. Absolutely everything should be logged and displayed in the console window.

**Comment by tgillian** [comment] 2024-06-16 18:57
Sorry, no change.  Did echo all in command console.

[RepairKit.log](https://github.com/user-attachments/files/15859547/RepairKit.log)

**Comment by Foulest** [comment] 2024-06-16 18:59
Can you copy and paste the command console output into a log/txt file?

**Comment by tgillian** [comment] 2024-06-16 19:10
Yep, in two files.  (snippet).  PGN files.

![Screenshot 2024-06-16 120712](https://github.com/Foulest/RepairKit/assets/172927930/4fad3ad0-e1a8-408f-bd43-2e72348a9925)
![Screenshot 2024-06-16 120745](https://github.com/Foulest/RepairKit/assets/172927930/3fe651d7-ab9f-4c45-8359-07021a52666b)

**Comment by Foulest** [comment] 2024-06-16 19:11
Bingo. There's the problem. Okay. Fixing now.

**Comment by Foulest** [comment] 2024-06-16 19:23
Should be fixed. For peace of mind, let's do the same thing again. Run this [newly compiled build](https://www.dropbox.com/scl/fi/qc3csjyfh2xxusb91spfs/RepairKit-1.0.8-Test.zip?rlkey=b6vu77m5rh4byar06l9pu3l07&st=wvvnj1nq&dl=1) from the `start.bat` file after extracting it and send screenshots of the console.

**Comment by tgillian** [comment] 2024-06-16 19:44
Touchdown!  Don't know what you did but it works.  What was the problem?

Thanks for your patience and assistance!

**Comment by Foulest** [comment] 2024-06-16 19:47
For some reason, your system required missing accessibility features that no other system has needed when creating the GUI. I'm not sure if you have any accessibility settings enabled, but it tried to load something in the accessibility package that was not found. I've since added it. This was a whirlwind of an issue. Thank you for your patience as well! Shipping an update right now.

**Closed by Foulest** 2024-06-16 19:47 UTC
Labels: bug
